version: '3'
services:
  daily-counter:
    image: mausved/daily-counter
    build: .
    container_name: daily-counter
    depends_on:
      - database

  database:
    image: postgres
    container_name: daily-counter-db
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - ./migrations:/docker-entrypoint-initdb.d/
      - daily-counter-db:/var/lib/postgresql/data

volumes:
    daily-counter-db: