version: '3'
services:
  daily-counter:
    image: mausved/daily-counter
    build: .
    container_name: daily-counter
    environment:
      TELEGRAM_BOT_API_TOKEN: ${TELEGRAM_BOT_API_TOKEN}
      POSTGRES_DSN: ${POSTGRES_DSN}
    depends_on:
      - database

  database:
    image: postgres
    container_name: daily-counter-db
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DATABASE: ${POSTGRES_DATABASE}
    volumes:
      - ./migrations:/docker-entrypoint-initdb.d/
      - daily-counter-db:/var/lib/postgresql/data

volumes:
    daily-counter-db: