name: deploy
on: [pull_request]

env:
  USER: mausved
  HOST: 158.160.119.46
  PATH: /home/mausved/dailycounter

jobs:
  deploy:
    name: deploy
    runs-on: ubuntu-latest
    steps:
      - name: Install SSH Key
        uses: shimataro/ssh-key-action@v2
        with:
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          known_hosts: 'just-a-placeholder-so-we-dont-get-errors'
      - name: Adding Known Hosts
        run: ssh-keyscan -H ${{ secrets.HOST }} >> ~/.ssh/known_hosts
      - name: Check out code into the Go module directory
        uses: actions/checkout@v3
      - name: deploy
        env:
          USER: ${{ env.USER }}
          HOST: ${{ env.HOST }}
          PATH: ${{ env.PATH }}
        run: bash ./deploy.sh
