name: deploy
on: [pull_request]

env:
  HOST: "62.84.117.24"
  USER: "mausved"

jobs:
  deploy:
    name: deploy
    runs-on: ubuntu-latest
    steps:
      - name: Install SSH Key
        uses: shimataro/ssh-key-action@v2
        with:
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          known_hosts: 'just-a-placeholder-so-we-dont-get-errors'
      - name: Adding Known Hosts
        run: ssh-keyscan -H ${{env.HOST}} >> ~/.ssh/known_hosts
      - name: Check out code into the Go module directory
        uses: actions/checkout@v3
      - name: deploy
        run: bash ./deploy.sh
