name: deploy
on: [pull_request]

env:
  HOST: "62.84.117.24"
  USER: "mausved"

jobs:
  deploy:
    name: deploy
    runs-on: ubuntu-latest
    steps:
      - name: Install SSH Key
        uses: shimataro/ssh-key-action@v2
        with:
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          known_hosts: 'just-a-placeholder-so-we-dont-get-errors'
      - name: Adding Known Hosts
        run: ssh-keyscan -H ${{env.HOST}} >> ~/.ssh/known_hosts
      - name: Check out code into the Go module directory
        uses: actions/checkout@v3
      - name: Deploy with rsync
        run: rsync -avz . ${{env.USER}}@${{env.HOST}}:/home/mausved/dailycounter
      - name: install tmux
        run: sudo apt-get update && sudo apt-get -y install tmux
      - name: tmux ls
        run: tmux ls
      - name: stop
        run: tmux kill-session -t daily_counter
