name: deploy
on:
  pull_request:

jobs:
  deploy:
    name: deploy
    runs-on: ubuntu-latest
    steps:
      - name: Install SSH Key
        uses: shimataro/ssh-key-action@v2
        with:
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          known_hosts: 'just-a-placeholder-so-we-dont-get-errors'
      - name: Adding Known Hosts
        run: ssh-keyscan -H ${{ secrets.SSH_HOST }} >> ~/.ssh/known_hosts
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Check out code into the Go module directory
        uses: actions/checkout@v3
      - name: Build image
        run: docker-compose build
      - name: Push image
        run: docker-compose push
      - name: Deploy
        env:
          POSTGRES_DSN: ${{ secrets.POSTGRES_DSN }}
          POSTGRES_USER: ${{ secrets.POSTGRES_USER }}
          POSTGRES_PASSWORD: ${{ secrets.POSTGRES_PASSWORD }}
          POSTGRES_DATABASE: ${{ secrets.POSTGRES_DATABASE }}
          TELEGRAM_BOT_API_TOKEN: ${{ secrets.TELEGRAM_BOT_API_TOKEN }}
        run: |
          ssh ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }} "rm /home/mausved/dailycounter/.env || true"
          ssh ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }} "echo TELEGRAM_BOT_API_TOKEN=${TELEGRAM_BOT_API_TOKEN} >> /home/mausved/dailycounter/.env"
          ssh ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }} "echo POSTGRES_USER=${POSTGRES_USER} >> /home/mausved/dailycounter/.env"
          ssh ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }} "echo POSTGRES_PASSWORD${POSTGRES_PASSWORD} >> /home/mausved/dailycounter/.env"
          ssh ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }} "echo POSTGRES_DATABASE=${POSTGRES_DATABASE} >> /home/mausved/dailycounter/.env"
          ssh ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }} "echo POSTGRES_DSN=${POSTGRES_DSN} >> /home/mausved/dailycounter/.env"
          
          rsync -avz ./docker-compose.yaml  ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }}:/home/mausved/dailycounter/docker-compose.yaml
          restart() {
          
          cd /home/mausved/dailycounter/
          docker-compose pull
          docker-compose down
          docker-compose up -d
          }
          ssh ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }} "$(typeset -f); restart"
