name: deploy
on: [ pull_request ]

env:
  IP: "62.84.117.24"
  USER: "mausved"

jobs:
  deploy:
    name: deploy
    runs-on: ubuntu-latest
    steps:
      - name: ssh connect
        run: ssh $USER@$IP 'cd dailycounter && go run main.go processor.go'
