name: deploy
on:
  pull_request:

jobs:
  deploy:
    name: deploy
    runs-on: ubuntu-latest
    steps:
      - name: Install SSH Key
        uses: shimataro/ssh-key-action@v2
        with:
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          known_hosts: 'just-a-placeholder-so-we-dont-get-errors'
      - name: Adding Known Hosts
        run: ssh-keyscan -H ${{ secrets.SSH_HOST }} >> ~/.ssh/known_hosts
      - name: Check out code into the Go module directory
        uses: actions/checkout@v3
      - name: Build image
        run: docker-compose build
      - name: Push image
        run: docker-compose push
      - name: Deploy
        run: |
          rsync -avz ./docker-compose.yaml  ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }}:/home/mausved/dailycounter/docker-compose.yaml
          restart() {
          docker-compose pull
          docker-compose down
          docker-compose up -d
          }
          ssh ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }} "$(typeset -f); restart"
