name: deploy
on:
  push:

jobs:
  deploy:
    name: deploy
    runs-on: ubuntu-latest
    steps:
      - name: Install SSH Key
        uses: shimataro/ssh-key-action@v2
        with:
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          known_hosts: 'just-a-placeholder-so-we-dont-get-errors'
      - name: Adding Known Hosts
        run: ssh-keyscan -H ${{ secrets.SSH_HOST }} >> ~/.ssh/known_hosts
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Check out code into the Go module directory
        uses: actions/checkout@v3
      - name: Build image
        run: docker-compose build
      - name: Push image
        run: docker-compose push
      - name: Deploy
        env:
          POSTGRES_DSN: ${{ secrets.POSTGRES_DSN }}
          POSTGRES_USER: ${{ secrets.POSTGRES_USER }}
          POSTGRES_PASSWORD: ${{ secrets.POSTGRES_PASSWORD }}
          POSTGRES_DB: ${{ secrets.POSTGRES_DB }}
          TELEGRAM_BOT_API_TOKEN: ${{ secrets.TELEGRAM_BOT_API_TOKEN }}
        run: |
          echo TELEGRAM_BOT_API_TOKEN=${TELEGRAM_BOT_API_TOKEN} >> .env
          echo POSTGRES_USER=${POSTGRES_USER} >> .env
          echo POSTGRES_PASSWORD=${POSTGRES_PASSWORD} >> .env
          echo POSTGRES_DB=${POSTGRES_DB} >> .env
          echo POSTGRES_DSN=${POSTGRES_DSN} >> .env
          
          rsync -avz ./.env  ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }}:/home/mausved/dailycounter/.env
          rsync -avz ./docker-compose.yaml  ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }}:/home/mausved/dailycounter/docker-compose.yaml
          rsync -avz ./migrations/  ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }}:/home/mausved/dailycounter/migrations/
          
          restart() {
          cd /home/mausved/dailycounter/
          docker-compose down
          docker-compose up -d
          }
          
          ssh ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }} "$(typeset -f); restart"
