name: deploy
on:
  pull_request:
#    types:
#      - closed

jobs:
  deploy:
    name: deploy
    runs-on: ubuntu-latest
    steps:
      - name: Install SSH Key
        uses: shimataro/ssh-key-action@v2
        with:
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          known_hosts: 'just-a-placeholder-so-we-dont-get-errors'
      - name: Adding Known Hosts
        run: ssh-keyscan -H ${{ secrets.SSH_HOST }} >> ~/.ssh/known_hosts
      - name: Check out code into the Go module directory
        uses: actions/checkout@v3
      - name: Deploy
        run: |
          session="daily_counter"
          env GOOS=linux GOARCH=amd64 go build -o $session main.go processor.go
          rsync -avz ./$session  ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }}:${{ secrets.SSH_PATH }}
  
          restart() {
          session="daily_counter"
          pid=$(ps -e | grep ${session} | grep -v 'grep' | awk '{print $1}')
          echo "pid=$pid"
          
          if [[ $pid -ne '' ]]
          then
            kill -2 $pid
            wait $pid
            echo "stopped pid=$pid"
            tmux kill-session -t $session
            echo "killed session $session"
          else
            echo "not found already running app"
          fi
            tmux new-session -d -s $session "cd dailycounter && ./$session"
            echo "started app"
          }
          ssh ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }} "$(typeset -f); restart"
          rm $session
