name: deploy
on:
  pull_request:
    types:
      - closed

env:
  HOST: "62.84.117.24"
  USER: "mausved"

jobs:
  deploy:
    name: deploy
    runs-on: ubuntu-latest
    steps:
      - name: Install SSH Key
        uses: shimataro/ssh-key-action@v2
        with:
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          known_hosts: 'just-a-placeholder-so-we-dont-get-errors'
      - name: Adding Known Hosts
        run: ssh-keyscan -H ${{env.HOST}} >> ~/.ssh/known_hosts
      - name: Deploy with rsync
        run: rsync -avz . ${{env.USER}}@${{env.HOST}}:/home/mausved/dailycounter/
      - name: stop previous
        run: ssh ${{env.USER}}@${{env.HOST}} "ps | grep '\./main' | grep -v 'grep' | awk '{print $1}' | xargs kill -2 {}"
      - name: start new
        run: ssh ${{env.USER}}@${{env.HOST}} "tmux new-session -d -s daily_counter 'cd dailycounter && go build -o main main.go processor.go && ./main'"
